# Package Overview
package_name: plant_disease_model
 
# Data Files
kagglehub:
  dataset: "vipoooool/new-plant-diseases-dataset"
  output_dir: "./dataset"

# Data Files
data_dir: ./dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/
test_data_dir: ./dataset/test/


pipeline_name: plant_disease_model
pipeline_save_file: plant_disease_model_v
 
# Set train/test split
test_size: 0.20
 
# Set the random seed
random_state: 42
 
# Alogrithm parameters
epochs: 1
batch_size: 64